/*
 * Copyright (c) 2007, TopCoder, Inc. All rights reserved.
 */

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ServiceModel;
using System.ServiceModel.Channels;
using HermesNS.TC.Services.ScheduleItem.Entities;
using HermesNS.TC.Entity.Validation;
using TopCoder.Services.WCF;

namespace HermesNS.TC.Services.ScheduleItem.Clients
{
    /// <summary>
    /// svcutil generated code
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [ServiceContractAttribute(ConfigurationName = "HermesScheduleItemService")]
    [HermesNS.TC.CoverageExcludeAttribute]
    public interface HermesScheduleItemService
    {
        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="name">svcutil generated code</param>
        /// <param name="type">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/CreateActivity",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateActivityResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityTCFaultExceptionFault",
            Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivity CreateActivity(string name, HermesActivityType type);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityGroup",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateActivityGroupResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityGroupHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityGroupTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivityGroup CreateActivityGroup(string abbreviation);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <param name="activityGroup">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityType",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateActivityTypeResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityTypeTCFaultExceptionFault",
            Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateActivityTypeHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivityType CreateActivityType(string abbreviation, HermesActivityGroup activityGroup);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="workDate">svcutil generated code</param>
        /// <param name="activity">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItem",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemTCFaultExceptionFault",
            Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem CreateScheduleItem(System.DateTime workDate, HermesActivity activity);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="description">svcutil generated code</param>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemStatusHermesValida" +
            "tionFaultExceptionFault", Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItemStatus CreateScheduleItemStatus(string abbreviation, string description);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <param name="description">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemRequestStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemRequestStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemRequestStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemRequestStatusHerme" +
            "sValidationFaultExceptionFault", Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItemRequestStatus CreateScheduleItemRequestStatus(string abbreviation, string description);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivity",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteActivityResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteActivity(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivities",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteActivitiesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivitiesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteActivities(IList<string> ids);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityGroup",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteActivityGroupResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityGroupTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteActivityGroup(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityGroups",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteActivityGroupsResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityGroupsTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteActivityGroups(IList<string> ids);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        [OperationContractAttribute(
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityType",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteActivityTypeResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityTypeTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteActivityType(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityTypes",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteActivityTypesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteActivityTypesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteActivityTypes(IList<string> ids);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItem",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItem(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItems",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemsResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemsTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItems(IList<string> ids);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItemStatus(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemStatuses",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemStatusesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemStatusesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItemStatuses(IList<string> ids);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemRequestStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemRequestStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemRequestStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItemRequestStatus(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemRequestStatuses",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemRequestStatusesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemRequestStatusesTCFaultExceptionFault",
            Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItemRequestStatuses(IList<string> ids);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetActivity",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetActivityResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetActivityTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivity GetActivity(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetActivityGroup",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetActivityGroupResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetActivityGroupTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivityGroup GetActivityGroup(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetActivityType",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetActivityTypeResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetActivityTypeTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivityType GetActivityType(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItem",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem GetScheduleItem(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItemStatus GetScheduleItemStatus(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemRequestStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemRequestStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemRequestStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItemRequestStatus GetScheduleItemRequestStatus(string id);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="showDisabled">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetAllActivities",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetAllActivitiesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetAllActivitiesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesActivity> GetAllActivities(bool showDisabled);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetAllActivityGroups",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetAllActivityGroupsResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetAllActivityGroupsTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesActivityGroup> GetAllActivityGroups();

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetAllActivityTypes",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetAllActivityTypesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetAllActivityTypesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesActivityType> GetAllActivityTypes();

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetAllScheduleItemRequestStatuses",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetAllScheduleItemRequestStatusesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetAllScheduleItemRequestStatusesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesScheduleItemRequestStatus> GetAllScheduleItemRequestStatuses();

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetAllScheduleItemStatuses",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetAllScheduleItemStatusesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetAllScheduleItemStatusesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesScheduleItemStatus> GetAllScheduleItemStatuses();

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activity">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveActivity",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveActivityResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityTCFaultExceptionFault",
            Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivity SaveActivity(HermesActivity activity);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityGroup">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroup",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroupResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroupHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroupTCFaultExceptionFault",
            Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivityGroup SaveActivityGroup(HermesActivityGroup activityGroup);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityType">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityType",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypeResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypeHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypeTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesActivityType SaveActivityType(HermesActivityType activityType);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItem">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItem",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem SaveScheduleItem(HermesScheduleItem scheduleItem);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItemStatus">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatusHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItemStatus SaveScheduleItemStatus(HermesScheduleItemStatus scheduleItemStatus);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleRequestStatus">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatus",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatusResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatusTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatusHermesV" +
            "alidationFaultExceptionFault", Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItemRequestStatus SaveScheduleItemRequestStatus(
            HermesScheduleItemRequestStatus scheduleRequestStatus);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activities">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveActivities",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveActivitiesResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivitiesHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivitiesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesActivity> SaveActivities(IList<HermesActivity> activities);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityGroups">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroups",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroupsResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroupsHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityGroupsTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesActivityGroup> SaveActivityGroups(IList<HermesActivityGroup> activityGroups);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityTypes">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypes",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveActivityTypesHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesActivityType> SaveActivityTypes(IList<HermesActivityType> activityTypes);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleRequestStatuses">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatuses",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatusesResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatusesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemRequestStatusesHerme" +
            "sValidationFaultExceptionFault", Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesScheduleItemRequestStatus> SaveScheduleItemRequestStatuses(
            IList<HermesScheduleItemRequestStatus> scheduleRequestStatuses);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItems">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItems",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemsResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemsTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemsHermesValidationFaultExceptionFault",
            Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesScheduleItem> SaveScheduleItems(IList<HermesScheduleItem> scheduleItems);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItemStatuses">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatuses",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatusesResponse")]
        [FaultContractAttribute(typeof(HermesValidationFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatusesHermesValidationFault" +
            "ExceptionFault", Name = "HermesValidationFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/HermesNS.TC.Entity.Validation")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/SaveScheduleItemStatusesTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        IList<HermesScheduleItemStatus> SaveScheduleItemStatuses(IList<HermesScheduleItemStatus> scheduleItemStatuses);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="parent">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemEditCopy",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemEditCopyResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemEditCopyTCFaultExceptionFault",
            Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem CreateScheduleItemEditCopy(HermesScheduleItem parent);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="parent">svcutil generated code</param>
        /// <param name="editCopy">svcutil generated code</param>
        [OperationContractAttribute(
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemPublishEditCopyRelationship",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemPublishEditCopyRel" +
            "ationshipResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/CreateScheduleItemPublishEditCopyRel" +
            "ationshipTCFaultExceptionFault", Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void CreateScheduleItemPublishEditCopyRelationship(HermesScheduleItem parent, HermesScheduleItem editCopy);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="editCopy">svcutil generated code</param>
        [OperationContractAttribute(
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemPublishEditCopyRel" +
            "ationship", ReplyAction = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemPublishEditCopyRel" +
            "ationshipResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/DeleteScheduleItemPublishEditCopyRel" +
            "ationshipTCFaultExceptionFault", Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        void DeleteScheduleItemPublishEditCopyRelationship(HermesScheduleItem editCopy);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="parent">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemEditCopy",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemEditCopyResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemEditCopyTCFaultExcept" +
            "ionFault", Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem GetScheduleItemEditCopy(HermesScheduleItem parent);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="editCopy">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemParentCopy",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemParentCopyResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/GetScheduleItemParentCopyTCFaultExce" +
            "ptionFault", Name = "TCFaultException",
            Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem GetScheduleItemParentCopy(HermesScheduleItem editCopy);

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="editCopy">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        [OperationContractAttribute(Action = "http://tempuri.org/HermesScheduleItemService/PublishScheduleItem",
            ReplyAction = "http://tempuri.org/HermesScheduleItemService/PublishScheduleItemResponse")]
        [FaultContractAttribute(typeof(TCFaultException),
            Action = "http://tempuri.org/HermesScheduleItemService/PublishScheduleItemTCFaultExceptionF" +
            "ault", Name = "TCFaultException", Namespace = "http://schemas.datacontract.org/2004/07/TopCoder.Services.WCF")]
        [TransactionFlow(TransactionFlowOption.Mandatory)]
        HermesScheduleItem PublishScheduleItem(HermesScheduleItem editCopy);
    }

    /// <summary>
    /// svcutil generated code
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [HermesNS.TC.CoverageExcludeAttribute]
    public interface HermesScheduleItemServiceChannel : HermesScheduleItemService, IClientChannel
    {
    }

    /// <summary>
    /// svcutil generated code
    /// </summary>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [HermesNS.TC.CoverageExcludeAttribute]
    public partial class HermesScheduleItemServiceClient : ClientBase<HermesScheduleItemService>, HermesScheduleItemService
    {

        /// <summary>
        /// svcutil generated code
        /// </summary>
        public HermesScheduleItemServiceClient()
        {
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="endpointConfigurationName">svcutil generated code</param>
        public HermesScheduleItemServiceClient(string endpointConfigurationName)
            :
                base(endpointConfigurationName)
        {
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="endpointConfigurationName">svcutil generated code</param>
        /// <param name="remoteAddress">svcutil generated code</param>
        public HermesScheduleItemServiceClient(string endpointConfigurationName, string remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="endpointConfigurationName">svcutil generated code</param>
        /// <param name="remoteAddress">svcutil generated code</param>
        public HermesScheduleItemServiceClient(string endpointConfigurationName, EndpointAddress remoteAddress)
            :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="binding">svcutil generated code</param>
        /// <param name="remoteAddress">svcutil generated code</param>
        public HermesScheduleItemServiceClient(Binding binding, EndpointAddress remoteAddress)
            :
                base(binding, remoteAddress)
        {
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="name">svcutil generated code</param>
        /// <param name="type">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivity CreateActivity(string name, HermesActivityType type)
        {
            return base.Channel.CreateActivity(name, type);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivityGroup CreateActivityGroup(string abbreviation)
        {
            return base.Channel.CreateActivityGroup(abbreviation);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <param name="activityGroup">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivityType CreateActivityType(string abbreviation, HermesActivityGroup activityGroup)
        {
            return base.Channel.CreateActivityType(abbreviation, activityGroup);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="workDate">svcutil generated code</param>
        /// <param name="activity">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem CreateScheduleItem(System.DateTime workDate, HermesActivity activity)
        {
            return base.Channel.CreateScheduleItem(workDate, activity);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="description">svcutil generated code</param>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItemStatus CreateScheduleItemStatus(string abbreviation, string description)
        {
            return base.Channel.CreateScheduleItemStatus(abbreviation, description);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="abbreviation">svcutil generated code</param>
        /// <param name="description">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItemRequestStatus CreateScheduleItemRequestStatus(string abbreviation, string description)
        {
            return base.Channel.CreateScheduleItemRequestStatus(abbreviation, description);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        public void DeleteActivity(string id)
        {
            base.Channel.DeleteActivity(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        public void DeleteActivities(IList<string> ids)
        {
            base.Channel.DeleteActivities(ids);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        public void DeleteActivityGroup(string id)
        {
            base.Channel.DeleteActivityGroup(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        public void DeleteActivityGroups(IList<string> ids)
        {
            base.Channel.DeleteActivityGroups(ids);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        public void DeleteActivityType(string id)
        {
            base.Channel.DeleteActivityType(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        public void DeleteActivityTypes(IList<string> ids)
        {
            base.Channel.DeleteActivityTypes(ids);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        public void DeleteScheduleItem(string id)
        {
            base.Channel.DeleteScheduleItem(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        public void DeleteScheduleItems(IList<string> ids)
        {
            base.Channel.DeleteScheduleItems(ids);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        public void DeleteScheduleItemStatus(string id)
        {
            base.Channel.DeleteScheduleItemStatus(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        public void DeleteScheduleItemStatuses(IList<string> ids)
        {
            base.Channel.DeleteScheduleItemStatuses(ids);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        public void DeleteScheduleItemRequestStatus(string id)
        {
            base.Channel.DeleteScheduleItemRequestStatus(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="ids">svcutil generated code</param>
        public void DeleteScheduleItemRequestStatuses(IList<string> ids)
        {
            base.Channel.DeleteScheduleItemRequestStatuses(ids);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivity GetActivity(string id)
        {
            return base.Channel.GetActivity(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivityGroup GetActivityGroup(string id)
        {
            return base.Channel.GetActivityGroup(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivityType GetActivityType(string id)
        {
            return base.Channel.GetActivityType(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem GetScheduleItem(string id)
        {
            return base.Channel.GetScheduleItem(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItemStatus GetScheduleItemStatus(string id)
        {
            return base.Channel.GetScheduleItemStatus(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="id">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItemRequestStatus GetScheduleItemRequestStatus(string id)
        {
            return base.Channel.GetScheduleItemRequestStatus(id);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="showDisabled">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesActivity> GetAllActivities(bool showDisabled)
        {
            return base.Channel.GetAllActivities(showDisabled);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        public IList<HermesActivityGroup> GetAllActivityGroups()
        {
            return base.Channel.GetAllActivityGroups();
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        public IList<HermesActivityType> GetAllActivityTypes()
        {
            return base.Channel.GetAllActivityTypes();
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        public IList<HermesScheduleItemRequestStatus> GetAllScheduleItemRequestStatuses()
        {
            return base.Channel.GetAllScheduleItemRequestStatuses();
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <returns>svcutil generated code</returns>
        public IList<HermesScheduleItemStatus> GetAllScheduleItemStatuses()
        {
            return base.Channel.GetAllScheduleItemStatuses();
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activity">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivity SaveActivity(HermesActivity activity)
        {
            return base.Channel.SaveActivity(activity);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityGroup">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivityGroup SaveActivityGroup(HermesActivityGroup activityGroup)
        {
            return base.Channel.SaveActivityGroup(activityGroup);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityType">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesActivityType SaveActivityType(HermesActivityType activityType)
        {
            return base.Channel.SaveActivityType(activityType);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItem">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem SaveScheduleItem(HermesScheduleItem scheduleItem)
        {
            return base.Channel.SaveScheduleItem(scheduleItem);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItemStatus">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItemStatus SaveScheduleItemStatus(HermesScheduleItemStatus scheduleItemStatus)
        {
            return base.Channel.SaveScheduleItemStatus(scheduleItemStatus);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleRequestStatus">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItemRequestStatus SaveScheduleItemRequestStatus(
            HermesScheduleItemRequestStatus scheduleRequestStatus)
        {
            return base.Channel.SaveScheduleItemRequestStatus(scheduleRequestStatus);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activities">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesActivity> SaveActivities(IList<HermesActivity> activities)
        {
            return base.Channel.SaveActivities(activities);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityGroups">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesActivityGroup> SaveActivityGroups(IList<HermesActivityGroup> activityGroups)
        {
            return base.Channel.SaveActivityGroups(activityGroups);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="activityTypes">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesActivityType> SaveActivityTypes(IList<HermesActivityType> activityTypes)
        {
            return base.Channel.SaveActivityTypes(activityTypes);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleRequestStatuses">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesScheduleItemRequestStatus> SaveScheduleItemRequestStatuses(
            IList<HermesScheduleItemRequestStatus> scheduleRequestStatuses)
        {
            return base.Channel.SaveScheduleItemRequestStatuses(scheduleRequestStatuses);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItems">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesScheduleItem> SaveScheduleItems(IList<HermesScheduleItem> scheduleItems)
        {
            return base.Channel.SaveScheduleItems(scheduleItems);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="scheduleItemStatuses">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public IList<HermesScheduleItemStatus> SaveScheduleItemStatuses(
            IList<HermesScheduleItemStatus> scheduleItemStatuses)
        {
            return base.Channel.SaveScheduleItemStatuses(scheduleItemStatuses);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="parent">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem CreateScheduleItemEditCopy(HermesScheduleItem parent)
        {
            return base.Channel.CreateScheduleItemEditCopy(parent);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="parent">svcutil generated code</param>
        /// <param name="editCopy">svcutil generated code</param>
        public void CreateScheduleItemPublishEditCopyRelationship(HermesScheduleItem parent, HermesScheduleItem editCopy)
        {
            base.Channel.CreateScheduleItemPublishEditCopyRelationship(parent, editCopy);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="editCopy">svcutil generated code</param>
        public void DeleteScheduleItemPublishEditCopyRelationship(HermesScheduleItem editCopy)
        {
            base.Channel.DeleteScheduleItemPublishEditCopyRelationship(editCopy);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="parent">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem GetScheduleItemEditCopy(HermesScheduleItem parent)
        {
            return base.Channel.GetScheduleItemEditCopy(parent);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="editCopy">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem GetScheduleItemParentCopy(HermesScheduleItem editCopy)
        {
            return base.Channel.GetScheduleItemParentCopy(editCopy);
        }

        /// <summary>
        /// svcutil generated code
        /// </summary>
        /// <param name="editCopy">svcutil generated code</param>
        /// <returns>svcutil generated code</returns>
        public HermesScheduleItem PublishScheduleItem(HermesScheduleItem editCopy)
        {
            return base.Channel.PublishScheduleItem(editCopy);
        }
    }
}