DELETE FROM SCHED_ITEM_PUBLISH_XREF;
DELETE FROM SCHED_ITEM_PUB_XREF_HIST;
DELETE FROM SCHED_ITEM;
DELETE FROM SCHED_ITEM_HIST;
DELETE FROM ACTIVITY;
DELETE FROM ACTIVITY_HIST;
DELETE FROM ACTIVITY_TYPE;
DELETE FROM ACTIVITY_TYPE_HIST;
DELETE FROM ACTIVITY_GROUP;
DELETE FROM ACTIVITY_GROUP_HIST;
DELETE FROM SCHED_STATUS;
DELETE FROM SCHED_STATUS_HIST;
DELETE FROM SCHED_REQUEST_STATUS;
DELETE FROM SCHED_REQUEST_STATUS_HIST;
COMMIT