//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for addressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="addressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}AddressGroup"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addressType", propOrder = {
    "rfc2822Address",
    "number",
    "shortCode"
})
@XmlSeeAlso({
    UserAgentInfoType.class
})
public class AddressType {

    @XmlElement(name = "RFC2822Address")
    protected AddressType.RFC2822Address rfc2822Address;
    @XmlElement(name = "Number")
    protected AddressType.Number number;
    @XmlElement(name = "ShortCode")
    protected AddressType.ShortCode shortCode;

    /**
     * Gets the value of the rfc2822Address property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType.RFC2822Address }
     *     
     */
    public AddressType.RFC2822Address getRFC2822Address() {
        return rfc2822Address;
    }

    /**
     * Sets the value of the rfc2822Address property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType.RFC2822Address }
     *     
     */
    public void setRFC2822Address(AddressType.RFC2822Address value) {
        this.rfc2822Address = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType.Number }
     *     
     */
    public AddressType.Number getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType.Number }
     *     
     */
    public void setNumber(AddressType.Number value) {
        this.number = value;
    }

    /**
     * Gets the value of the shortCode property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType.ShortCode }
     *     
     */
    public AddressType.ShortCode getShortCode() {
        return shortCode;
    }

    /**
     * Sets the value of the shortCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType.ShortCode }
     *     
     */
    public void setShortCode(AddressType.ShortCode value) {
        this.shortCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}addressSecurity"/>
     *       &lt;attribute name="displayOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Number {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Boolean displayOnly;
        @XmlAttribute
        protected AddressCodingType addressCoding;
        @XmlAttribute
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the displayOnly property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isDisplayOnly() {
            if (displayOnly == null) {
                return false;
            } else {
                return displayOnly;
            }
        }

        /**
         * Sets the value of the displayOnly property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDisplayOnly(Boolean value) {
            this.displayOnly = value;
        }

        /**
         * Gets the value of the addressCoding property.
         * 
         * @return
         *     possible object is
         *     {@link AddressCodingType }
         *     
         */
        public AddressCodingType getAddressCoding() {
            return addressCoding;
        }

        /**
         * Sets the value of the addressCoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressCodingType }
         *     
         */
        public void setAddressCoding(AddressCodingType value) {
            this.addressCoding = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}addressSecurity"/>
     *       &lt;attribute name="displayOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class RFC2822Address {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Boolean displayOnly;
        @XmlAttribute
        protected AddressCodingType addressCoding;
        @XmlAttribute
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the displayOnly property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isDisplayOnly() {
            if (displayOnly == null) {
                return false;
            } else {
                return displayOnly;
            }
        }

        /**
         * Sets the value of the displayOnly property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDisplayOnly(Boolean value) {
            this.displayOnly = value;
        }

        /**
         * Gets the value of the addressCoding property.
         * 
         * @return
         *     possible object is
         *     {@link AddressCodingType }
         *     
         */
        public AddressCodingType getAddressCoding() {
            return addressCoding;
        }

        /**
         * Sets the value of the addressCoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressCodingType }
         *     
         */
        public void setAddressCoding(AddressCodingType value) {
            this.addressCoding = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attGroup ref="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}addressSecurity"/>
     *       &lt;attribute name="displayOnly" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ShortCode {

        @XmlValue
        protected String value;
        @XmlAttribute
        protected Boolean displayOnly;
        @XmlAttribute
        protected AddressCodingType addressCoding;
        @XmlAttribute
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlID
        @XmlSchemaType(name = "ID")
        protected String id;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the displayOnly property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isDisplayOnly() {
            if (displayOnly == null) {
                return false;
            } else {
                return displayOnly;
            }
        }

        /**
         * Sets the value of the displayOnly property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setDisplayOnly(Boolean value) {
            this.displayOnly = value;
        }

        /**
         * Gets the value of the addressCoding property.
         * 
         * @return
         *     possible object is
         *     {@link AddressCodingType }
         *     
         */
        public AddressCodingType getAddressCoding() {
            return addressCoding;
        }

        /**
         * Sets the value of the addressCoding property.
         * 
         * @param value
         *     allowed object is
         *     {@link AddressCodingType }
         *     
         */
        public void setAddressCoding(AddressCodingType value) {
            this.addressCoding = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

    }

}
