//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chargedPartyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="chargedPartyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Sender"/>
 *     &lt;enumeration value="Recipient"/>
 *     &lt;enumeration value="Both"/>
 *     &lt;enumeration value="Neither"/>
 *     &lt;enumeration value="ThirdParty"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "chargedPartyType")
@XmlEnum
public enum ChargedPartyType {

    @XmlEnumValue("Sender")
    SENDER("Sender"),
    @XmlEnumValue("Recipient")
    RECIPIENT("Recipient"),
    @XmlEnumValue("Both")
    BOTH("Both"),
    @XmlEnumValue("Neither")
    NEITHER("Neither"),
    @XmlEnumValue("ThirdParty")
    THIRD_PARTY("ThirdParty");
    private final String value;

    ChargedPartyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChargedPartyType fromValue(String v) {
        for (ChargedPartyType c: ChargedPartyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
