//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for deliverReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="deliverReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}genericRSReqType">
 *       &lt;sequence>
 *         &lt;element name="VASPID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}entityIDType" minOccurs="0"/>
 *         &lt;element name="VASID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}entityIDType" minOccurs="0"/>
 *         &lt;element name="LinkedID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}messageIDType" minOccurs="0"/>
 *         &lt;element name="Sender" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}addressType"/>
 *         &lt;element name="Recipients" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}recipientsType" minOccurs="0"/>
 *         &lt;element name="Previouslysentby" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}previouslySentByType" minOccurs="0"/>
 *         &lt;element name="Previouslysentdateandtime" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}previouslySentByDateTime" minOccurs="0"/>
 *         &lt;element name="SenderSPI" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}serviceProviderIDType" minOccurs="0"/>
 *         &lt;element name="RecipientSPI" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}serviceProviderIDType" minOccurs="0"/>
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReplyChargingID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}messageIDType" minOccurs="0"/>
 *         &lt;element name="Priority" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}priorityType" minOccurs="0"/>
 *         &lt;element name="Subject" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReplyApplicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuxApplicInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UACapabilities" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}capabilitiesType" minOccurs="0"/>
 *         &lt;element name="Content" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}contentReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "deliverReqType", propOrder = {
    "vaspid",
    "vasid",
    "linkedID",
    "sender",
    "recipients",
    "previouslysentby",
    "previouslysentdateandtime",
    "senderSPI",
    "recipientSPI",
    "timeStamp",
    "replyChargingID",
    "priority",
    "subject",
    "applicID",
    "replyApplicID",
    "auxApplicInfo",
    "uaCapabilities",
    "content"
})
public class DeliverReqType
    extends GenericRSReqType
{

    @XmlElement(name = "VASPID")
    protected String vaspid;
    @XmlElement(name = "VASID")
    protected String vasid;
    @XmlElement(name = "LinkedID")
    protected String linkedID;
    @XmlElement(name = "Sender", required = true)
    protected AddressType sender;
    @XmlElement(name = "Recipients")
    protected RecipientsType recipients;
    @XmlElement(name = "Previouslysentby")
    protected PreviouslySentByType previouslysentby;
    @XmlElement(name = "Previouslysentdateandtime")
    protected PreviouslySentByDateTime previouslysentdateandtime;
    @XmlElement(name = "SenderSPI")
    protected String senderSPI;
    @XmlElement(name = "RecipientSPI")
    protected String recipientSPI;
    @XmlElement(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "ReplyChargingID")
    protected String replyChargingID;
    @XmlElement(name = "Priority")
    protected PriorityType priority;
    @XmlElement(name = "Subject")
    protected String subject;
    @XmlElement(name = "ApplicID")
    protected String applicID;
    @XmlElement(name = "ReplyApplicID")
    protected String replyApplicID;
    @XmlElement(name = "AuxApplicInfo")
    protected String auxApplicInfo;
    @XmlElement(name = "UACapabilities")
    protected CapabilitiesType uaCapabilities;
    @XmlElement(name = "Content")
    protected ContentReferenceType content;

    /**
     * Gets the value of the vaspid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVASPID() {
        return vaspid;
    }

    /**
     * Sets the value of the vaspid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVASPID(String value) {
        this.vaspid = value;
    }

    /**
     * Gets the value of the vasid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVASID() {
        return vasid;
    }

    /**
     * Sets the value of the vasid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVASID(String value) {
        this.vasid = value;
    }

    /**
     * Gets the value of the linkedID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedID() {
        return linkedID;
    }

    /**
     * Sets the value of the linkedID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedID(String value) {
        this.linkedID = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setSender(AddressType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the recipients property.
     * 
     * @return
     *     possible object is
     *     {@link RecipientsType }
     *     
     */
    public RecipientsType getRecipients() {
        return recipients;
    }

    /**
     * Sets the value of the recipients property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecipientsType }
     *     
     */
    public void setRecipients(RecipientsType value) {
        this.recipients = value;
    }

    /**
     * Gets the value of the previouslysentby property.
     * 
     * @return
     *     possible object is
     *     {@link PreviouslySentByType }
     *     
     */
    public PreviouslySentByType getPreviouslysentby() {
        return previouslysentby;
    }

    /**
     * Sets the value of the previouslysentby property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviouslySentByType }
     *     
     */
    public void setPreviouslysentby(PreviouslySentByType value) {
        this.previouslysentby = value;
    }

    /**
     * Gets the value of the previouslysentdateandtime property.
     * 
     * @return
     *     possible object is
     *     {@link PreviouslySentByDateTime }
     *     
     */
    public PreviouslySentByDateTime getPreviouslysentdateandtime() {
        return previouslysentdateandtime;
    }

    /**
     * Sets the value of the previouslysentdateandtime property.
     * 
     * @param value
     *     allowed object is
     *     {@link PreviouslySentByDateTime }
     *     
     */
    public void setPreviouslysentdateandtime(PreviouslySentByDateTime value) {
        this.previouslysentdateandtime = value;
    }

    /**
     * Gets the value of the senderSPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSenderSPI() {
        return senderSPI;
    }

    /**
     * Sets the value of the senderSPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSenderSPI(String value) {
        this.senderSPI = value;
    }

    /**
     * Gets the value of the recipientSPI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecipientSPI() {
        return recipientSPI;
    }

    /**
     * Sets the value of the recipientSPI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecipientSPI(String value) {
        this.recipientSPI = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the replyChargingID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyChargingID() {
        return replyChargingID;
    }

    /**
     * Sets the value of the replyChargingID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyChargingID(String value) {
        this.replyChargingID = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link PriorityType }
     *     
     */
    public PriorityType getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorityType }
     *     
     */
    public void setPriority(PriorityType value) {
        this.priority = value;
    }

    /**
     * Gets the value of the subject property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubject() {
        return subject;
    }

    /**
     * Sets the value of the subject property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubject(String value) {
        this.subject = value;
    }

    /**
     * Gets the value of the applicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicID() {
        return applicID;
    }

    /**
     * Sets the value of the applicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicID(String value) {
        this.applicID = value;
    }

    /**
     * Gets the value of the replyApplicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyApplicID() {
        return replyApplicID;
    }

    /**
     * Sets the value of the replyApplicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyApplicID(String value) {
        this.replyApplicID = value;
    }

    /**
     * Gets the value of the auxApplicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxApplicInfo() {
        return auxApplicInfo;
    }

    /**
     * Sets the value of the auxApplicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxApplicInfo(String value) {
        this.auxApplicInfo = value;
    }

    /**
     * Gets the value of the uaCapabilities property.
     * 
     * @return
     *     possible object is
     *     {@link CapabilitiesType }
     *     
     */
    public CapabilitiesType getUACapabilities() {
        return uaCapabilities;
    }

    /**
     * Sets the value of the uaCapabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link CapabilitiesType }
     *     
     */
    public void setUACapabilities(CapabilitiesType value) {
        this.uaCapabilities = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ContentReferenceType }
     *     
     */
    public ContentReferenceType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentReferenceType }
     *     
     */
    public void setContent(ContentReferenceType value) {
        this.content = value;
    }

}
