//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for extendedreplaceReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="extendedreplaceReqType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MM7Version" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}versionType"/>
 *         &lt;element name="VASPID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}entityIDType" minOccurs="0"/>
 *         &lt;element name="VASID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}entityIDType" minOccurs="0"/>
 *         &lt;element name="ServiceCode" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}serviceCodeType" minOccurs="0"/>
 *         &lt;element name="ReplaceID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}messageIDType" minOccurs="0"/>
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="EarliestDeliveryTime" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}relativeOrAbsoluteDateType" minOccurs="0"/>
 *         &lt;element name="ExpiryDate" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}relativeOrAbsoluteDateType" minOccurs="0"/>
 *         &lt;element name="ReadReply" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DeliveryReport" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Content" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}contentReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extendedreplaceReqType", propOrder = {
    "mm7Version",
    "vaspid",
    "vasid",
    "serviceCode",
    "replaceID",
    "timeStamp",
    "earliestDeliveryTime",
    "expiryDate",
    "readReply",
    "deliveryReport",
    "content"
})
public class ExtendedreplaceReqType {

    @XmlElement(name = "MM7Version", required = true)
    protected String mm7Version;
    @XmlElement(name = "VASPID")
    protected String vaspid;
    @XmlElement(name = "VASID")
    protected String vasid;
    @XmlElement(name = "ServiceCode")
    protected ServiceCodeType serviceCode;
    @XmlElement(name = "ReplaceID")
    protected String replaceID;
    @XmlElement(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "EarliestDeliveryTime")
    protected String earliestDeliveryTime;
    @XmlElement(name = "ExpiryDate")
    protected String expiryDate;
    @XmlElement(name = "ReadReply")
    protected Boolean readReply;
    @XmlElement(name = "DeliveryReport")
    protected Boolean deliveryReport;
    @XmlElement(name = "Content")
    protected ContentReferenceType content;

    /**
     * Gets the value of the mm7Version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMM7Version() {
        return mm7Version;
    }

    /**
     * Sets the value of the mm7Version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMM7Version(String value) {
        this.mm7Version = value;
    }

    /**
     * Gets the value of the vaspid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVASPID() {
        return vaspid;
    }

    /**
     * Sets the value of the vaspid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVASPID(String value) {
        this.vaspid = value;
    }

    /**
     * Gets the value of the vasid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVASID() {
        return vasid;
    }

    /**
     * Sets the value of the vasid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVASID(String value) {
        this.vasid = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCodeType }
     *     
     */
    public ServiceCodeType getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCodeType }
     *     
     */
    public void setServiceCode(ServiceCodeType value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the replaceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaceID() {
        return replaceID;
    }

    /**
     * Sets the value of the replaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaceID(String value) {
        this.replaceID = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the earliestDeliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarliestDeliveryTime() {
        return earliestDeliveryTime;
    }

    /**
     * Sets the value of the earliestDeliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarliestDeliveryTime(String value) {
        this.earliestDeliveryTime = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpiryDate(String value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the readReply property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadReply() {
        return readReply;
    }

    /**
     * Sets the value of the readReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadReply(Boolean value) {
        this.readReply = value;
    }

    /**
     * Gets the value of the deliveryReport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDeliveryReport() {
        return deliveryReport;
    }

    /**
     * Sets the value of the deliveryReport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDeliveryReport(Boolean value) {
        this.deliveryReport = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ContentReferenceType }
     *     
     */
    public ContentReferenceType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentReferenceType }
     *     
     */
    public void setContent(ContentReferenceType value) {
        this.content = value;
    }

}
