//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for extendedcancelReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="extendedcancelReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}genericVASPRequestType">
 *       &lt;sequence>
 *         &lt;element name="CancelID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}messageIDType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "extendedcancelReqType", propOrder = {
    "cancelID"
})
public class ExtendedcancelReqType
    extends GenericVASPRequestType
{

    @XmlElement(name = "CancelID", required = true)
    protected String cancelID;

    /**
     * Gets the value of the cancelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelID() {
        return cancelID;
    }

    /**
     * Sets the value of the cancelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelID(String value) {
        this.cancelID = value;
    }

}
