//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MMStatusExtensionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MMStatusExtensionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RejectionByMMSRecipient"/>
 *     &lt;enumeration value="RejectionByOtherRS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MMStatusExtensionType")
@XmlEnum
public enum MMStatusExtensionType {

    @XmlEnumValue("RejectionByMMSRecipient")
    REJECTION_BY_MMS_RECIPIENT("RejectionByMMSRecipient"),
    @XmlEnumValue("RejectionByOtherRS")
    REJECTION_BY_OTHER_RS("RejectionByOtherRS");
    private final String value;

    MMStatusExtensionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MMStatusExtensionType fromValue(String v) {
        for (MMStatusExtensionType c: MMStatusExtensionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
