//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for multiAddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="multiAddressType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;group ref="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}AddressGroup"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "multiAddressType", propOrder = {
    "rfc2822AddressOrNumberOrShortCode"
})
public class MultiAddressType {

    @XmlElements({
        @XmlElement(name = "RFC2822Address", type = com.topcoder.alu.mock.mm7.entities.AddressType.RFC2822Address.class),
        @XmlElement(name = "ShortCode", type = com.topcoder.alu.mock.mm7.entities.AddressType.ShortCode.class),
        @XmlElement(name = "Number", type = com.topcoder.alu.mock.mm7.entities.AddressType.Number.class)
    })
    protected List<Object> rfc2822AddressOrNumberOrShortCode;

    /**
     * Gets the value of the rfc2822AddressOrNumberOrShortCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rfc2822AddressOrNumberOrShortCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRFC2822AddressOrNumberOrShortCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link com.topcoder.alu.mock.mm7.entities.AddressType.RFC2822Address }
     * {@link com.topcoder.alu.mock.mm7.entities.AddressType.ShortCode }
     * {@link com.topcoder.alu.mock.mm7.entities.AddressType.Number }
     * 
     * 
     */
    public List<Object> getRFC2822AddressOrNumberOrShortCode() {
        if (rfc2822AddressOrNumberOrShortCode == null) {
            rfc2822AddressOrNumberOrShortCode = new ArrayList<Object>();
        }
        return this.rfc2822AddressOrNumberOrShortCode;
    }

}
