//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.topcoder.alu.mock.mm7.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExtendedReplaceReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "extendedReplaceReq");
    private final static QName _SubmitRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "SubmitRsp");
    private final static QName _DeliveryReportReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "DeliveryReportReq");
    private final static QName _DeliverReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "DeliverReq");
    private final static QName _ExtendedCancelReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "extendedCancelReq");
    private final static QName _ReplaceReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "ReplaceReq");
    private final static QName _Body_QNAME = new QName("http://schemas.xmlsoap.org/soap/envelope/", "Body");
    private final static QName _SubmitReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "SubmitReq");
    private final static QName _Envelope_QNAME = new QName("http://schemas.xmlsoap.org/soap/envelope/", "Envelope");
    private final static QName _DeliveryReportRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "DeliveryReportRsp");
    private final static QName _ExtendedReplaceRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "extendedReplaceRsp");
    private final static QName _ReadReplyReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "ReadReplyReq");
    private final static QName _VASPErrorRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "VASPErrorRsp");
    private final static QName _RSErrorRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "RSErrorRsp");
    private final static QName _DeliverRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "DeliverRsp");
    private final static QName _Fault_QNAME = new QName("http://schemas.xmlsoap.org/soap/envelope/", "Fault");
    private final static QName _ReplaceRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "ReplaceRsp");
    private final static QName _ExtendedCancelRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "extendedCancelRsp");
    private final static QName _ReadReplyRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "ReadReplyRsp");
    private final static QName _CancelRsp_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "CancelRsp");
    private final static QName _CancelReq_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "CancelReq");
    private final static QName _Header_QNAME = new QName("http://schemas.xmlsoap.org/soap/envelope/", "Header");
    private final static QName _RecipientsTypeCc_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "Cc");
    private final static QName _RecipientsTypeBcc_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "Bcc");
    private final static QName _RecipientsTypeTo_QNAME = new QName("http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", "To");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.topcoder.alu.mock.mm7.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Fault }
     * 
     */
    public Fault createFault() {
        return new Fault();
    }

    /**
     * Create an instance of {@link TransactionID }
     * 
     */
    public TransactionID createTransactionID() {
        return new TransactionID();
    }

    /**
     * Create an instance of {@link ReplaceReqType }
     * 
     */
    public ReplaceReqType createReplaceReqType() {
        return new ReplaceReqType();
    }

    /**
     * Create an instance of {@link AddressType.ShortCode }
     * 
     */
    public AddressType.ShortCode createAddressTypeShortCode() {
        return new AddressType.ShortCode();
    }

    /**
     * Create an instance of {@link MultiAddressType }
     * 
     */
    public MultiAddressType createMultiAddressType() {
        return new MultiAddressType();
    }

    /**
     * Create an instance of {@link UserAgentDateTimeType }
     * 
     */
    public UserAgentDateTimeType createUserAgentDateTimeType() {
        return new UserAgentDateTimeType();
    }

    /**
     * Create an instance of {@link DeliverRspType }
     * 
     */
    public DeliverRspType createDeliverRspType() {
        return new DeliverRspType();
    }

    /**
     * Create an instance of {@link UserAgentInfoType }
     * 
     */
    public UserAgentInfoType createUserAgentInfoType() {
        return new UserAgentInfoType();
    }

    /**
     * Create an instance of {@link GenericVASPRequestType }
     * 
     */
    public GenericVASPRequestType createGenericVASPRequestType() {
        return new GenericVASPRequestType();
    }

    /**
     * Create an instance of {@link GenericResponseType }
     * 
     */
    public GenericResponseType createGenericResponseType() {
        return new GenericResponseType();
    }

    /**
     * Create an instance of {@link ExtendedcancelRspType }
     * 
     */
    public ExtendedcancelRspType createExtendedcancelRspType() {
        return new ExtendedcancelRspType();
    }

    /**
     * Create an instance of {@link ResponseStatusType }
     * 
     */
    public ResponseStatusType createResponseStatusType() {
        return new ResponseStatusType();
    }

    /**
     * Create an instance of {@link ExtendedreplaceReqType }
     * 
     */
    public ExtendedreplaceReqType createExtendedreplaceReqType() {
        return new ExtendedreplaceReqType();
    }

    /**
     * Create an instance of {@link ReadReplyReqType }
     * 
     */
    public ReadReplyReqType createReadReplyReqType() {
        return new ReadReplyReqType();
    }

    /**
     * Create an instance of {@link PreviouslySentByType }
     * 
     */
    public PreviouslySentByType createPreviouslySentByType() {
        return new PreviouslySentByType();
    }

    /**
     * Create an instance of {@link Envelope }
     * 
     */
    public Envelope createEnvelope() {
        return new Envelope();
    }

    /**
     * Create an instance of {@link CapabilitiesType }
     * 
     */
    public CapabilitiesType createCapabilitiesType() {
        return new CapabilitiesType();
    }

    /**
     * Create an instance of {@link SubmitReqType }
     * 
     */
    public SubmitReqType createSubmitReqType() {
        return new SubmitReqType();
    }

    /**
     * Create an instance of {@link RecipientsType }
     * 
     */
    public RecipientsType createRecipientsType() {
        return new RecipientsType();
    }

    /**
     * Create an instance of {@link DeliveryConditionType }
     * 
     */
    public DeliveryConditionType createDeliveryConditionType() {
        return new DeliveryConditionType();
    }

    /**
     * Create an instance of {@link SenderIDType }
     * 
     */
    public SenderIDType createSenderIDType() {
        return new SenderIDType();
    }

    /**
     * Create an instance of {@link AddressType.Number }
     * 
     */
    public AddressType.Number createAddressTypeNumber() {
        return new AddressType.Number();
    }

    /**
     * Create an instance of {@link ExtendedcancelresponseStatusType }
     * 
     */
    public ExtendedcancelresponseStatusType createExtendedcancelresponseStatusType() {
        return new ExtendedcancelresponseStatusType();
    }

    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link CancelReqType }
     * 
     */
    public CancelReqType createCancelReqType() {
        return new CancelReqType();
    }

    /**
     * Create an instance of {@link SubmitRspType }
     * 
     */
    public SubmitRspType createSubmitRspType() {
        return new SubmitRspType();
    }

    /**
     * Create an instance of {@link AnyDataType }
     * 
     */
    public AnyDataType createAnyDataType() {
        return new AnyDataType();
    }

    /**
     * Create an instance of {@link SubmitReqType.ReplyCharging }
     * 
     */
    public SubmitReqType.ReplyCharging createSubmitReqTypeReplyCharging() {
        return new SubmitReqType.ReplyCharging();
    }

    /**
     * Create an instance of {@link AddressType.RFC2822Address }
     * 
     */
    public AddressType.RFC2822Address createAddressTypeRFC2822Address() {
        return new AddressType.RFC2822Address();
    }

    /**
     * Create an instance of {@link ExtendedcancelReqType }
     * 
     */
    public ExtendedcancelReqType createExtendedcancelReqType() {
        return new ExtendedcancelReqType();
    }

    /**
     * Create an instance of {@link DeliverReqType }
     * 
     */
    public DeliverReqType createDeliverReqType() {
        return new DeliverReqType();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link ContentReferenceType }
     * 
     */
    public ContentReferenceType createContentReferenceType() {
        return new ContentReferenceType();
    }

    /**
     * Create an instance of {@link DeliveryReportReqType }
     * 
     */
    public DeliveryReportReqType createDeliveryReportReqType() {
        return new DeliveryReportReqType();
    }

    /**
     * Create an instance of {@link ExtendedreplaceRspType }
     * 
     */
    public ExtendedreplaceRspType createExtendedreplaceRspType() {
        return new ExtendedreplaceRspType();
    }

    /**
     * Create an instance of {@link GenericRSReqType }
     * 
     */
    public GenericRSReqType createGenericRSReqType() {
        return new GenericRSReqType();
    }

    /**
     * Create an instance of {@link ServiceCodeType }
     * 
     */
    public ServiceCodeType createServiceCodeType() {
        return new ServiceCodeType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link PreviouslySentByDateTime }
     * 
     */
    public PreviouslySentByDateTime createPreviouslySentByDateTime() {
        return new PreviouslySentByDateTime();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedreplaceReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "extendedReplaceReq")
    public JAXBElement<ExtendedreplaceReqType> createExtendedReplaceReq(ExtendedreplaceReqType value) {
        return new JAXBElement<ExtendedreplaceReqType>(_ExtendedReplaceReq_QNAME, ExtendedreplaceReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitRspType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "SubmitRsp")
    public JAXBElement<SubmitRspType> createSubmitRsp(SubmitRspType value) {
        return new JAXBElement<SubmitRspType>(_SubmitRsp_QNAME, SubmitRspType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliveryReportReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "DeliveryReportReq")
    public JAXBElement<DeliveryReportReqType> createDeliveryReportReq(DeliveryReportReqType value) {
        return new JAXBElement<DeliveryReportReqType>(_DeliveryReportReq_QNAME, DeliveryReportReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliverReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "DeliverReq")
    public JAXBElement<DeliverReqType> createDeliverReq(DeliverReqType value) {
        return new JAXBElement<DeliverReqType>(_DeliverReq_QNAME, DeliverReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedcancelReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "extendedCancelReq")
    public JAXBElement<ExtendedcancelReqType> createExtendedCancelReq(ExtendedcancelReqType value) {
        return new JAXBElement<ExtendedcancelReqType>(_ExtendedCancelReq_QNAME, ExtendedcancelReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReplaceReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "ReplaceReq")
    public JAXBElement<ReplaceReqType> createReplaceReq(ReplaceReqType value) {
        return new JAXBElement<ReplaceReqType>(_ReplaceReq_QNAME, ReplaceReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Body }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/soap/envelope/", name = "Body")
    public JAXBElement<Body> createBody(Body value) {
        return new JAXBElement<Body>(_Body_QNAME, Body.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubmitReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "SubmitReq")
    public JAXBElement<SubmitReqType> createSubmitReq(SubmitReqType value) {
        return new JAXBElement<SubmitReqType>(_SubmitReq_QNAME, SubmitReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Envelope }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/soap/envelope/", name = "Envelope")
    public JAXBElement<Envelope> createEnvelope(Envelope value) {
        return new JAXBElement<Envelope>(_Envelope_QNAME, Envelope.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "DeliveryReportRsp")
    public JAXBElement<GenericResponseType> createDeliveryReportRsp(GenericResponseType value) {
        return new JAXBElement<GenericResponseType>(_DeliveryReportRsp_QNAME, GenericResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedreplaceRspType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "extendedReplaceRsp")
    public JAXBElement<ExtendedreplaceRspType> createExtendedReplaceRsp(ExtendedreplaceRspType value) {
        return new JAXBElement<ExtendedreplaceRspType>(_ExtendedReplaceRsp_QNAME, ExtendedreplaceRspType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReadReplyReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "ReadReplyReq")
    public JAXBElement<ReadReplyReqType> createReadReplyReq(ReadReplyReqType value) {
        return new JAXBElement<ReadReplyReqType>(_ReadReplyReq_QNAME, ReadReplyReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "VASPErrorRsp")
    public JAXBElement<GenericResponseType> createVASPErrorRsp(GenericResponseType value) {
        return new JAXBElement<GenericResponseType>(_VASPErrorRsp_QNAME, GenericResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "RSErrorRsp")
    public JAXBElement<GenericResponseType> createRSErrorRsp(GenericResponseType value) {
        return new JAXBElement<GenericResponseType>(_RSErrorRsp_QNAME, GenericResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeliverRspType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "DeliverRsp")
    public JAXBElement<DeliverRspType> createDeliverRsp(DeliverRspType value) {
        return new JAXBElement<DeliverRspType>(_DeliverRsp_QNAME, DeliverRspType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/soap/envelope/", name = "Fault")
    public JAXBElement<Fault> createFault(Fault value) {
        return new JAXBElement<Fault>(_Fault_QNAME, Fault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "ReplaceRsp")
    public JAXBElement<GenericResponseType> createReplaceRsp(GenericResponseType value) {
        return new JAXBElement<GenericResponseType>(_ReplaceRsp_QNAME, GenericResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtendedcancelRspType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "extendedCancelRsp")
    public JAXBElement<ExtendedcancelRspType> createExtendedCancelRsp(ExtendedcancelRspType value) {
        return new JAXBElement<ExtendedcancelRspType>(_ExtendedCancelRsp_QNAME, ExtendedcancelRspType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "ReadReplyRsp")
    public JAXBElement<GenericResponseType> createReadReplyRsp(GenericResponseType value) {
        return new JAXBElement<GenericResponseType>(_ReadReplyRsp_QNAME, GenericResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GenericResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "CancelRsp")
    public JAXBElement<GenericResponseType> createCancelRsp(GenericResponseType value) {
        return new JAXBElement<GenericResponseType>(_CancelRsp_QNAME, GenericResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CancelReqType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "CancelReq")
    public JAXBElement<CancelReqType> createCancelReq(CancelReqType value) {
        return new JAXBElement<CancelReqType>(_CancelReq_QNAME, CancelReqType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Header }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.xmlsoap.org/soap/envelope/", name = "Header")
    public JAXBElement<Header> createHeader(Header value) {
        return new JAXBElement<Header>(_Header_QNAME, Header.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "Cc", scope = RecipientsType.class)
    public JAXBElement<MultiAddressType> createRecipientsTypeCc(MultiAddressType value) {
        return new JAXBElement<MultiAddressType>(_RecipientsTypeCc_QNAME, MultiAddressType.class, RecipientsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "Bcc", scope = RecipientsType.class)
    public JAXBElement<MultiAddressType> createRecipientsTypeBcc(MultiAddressType value) {
        return new JAXBElement<MultiAddressType>(_RecipientsTypeBcc_QNAME, MultiAddressType.class, RecipientsType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiAddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4", name = "To", scope = RecipientsType.class)
    public JAXBElement<MultiAddressType> createRecipientsTypeTo(MultiAddressType value) {
        return new JAXBElement<MultiAddressType>(_RecipientsTypeTo_QNAME, MultiAddressType.class, RecipientsType.class, value);
    }

}
