//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(
		namespace = "http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4",
		xmlns = { @javax.xml.bind.annotation.XmlNs( prefix = "env",
                namespaceURI = "http://schemas.xmlsoap.org/soap/envelope/" ) },
		elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.topcoder.alu.mock.mm7.entities;
