//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for readReplyReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="readReplyReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}genericRSReqType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}messageIDType"/>
 *         &lt;element name="Recipient" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}addressType"/>
 *         &lt;element name="Sender" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}addressType"/>
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="MMStatus" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}mmReadStatusType"/>
 *         &lt;element name="StatusText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ApplicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReplyApplicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuxApplicInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "readReplyReqType", propOrder = {
    "messageID",
    "recipient",
    "sender",
    "timeStamp",
    "mmStatus",
    "statusText",
    "applicID",
    "replyApplicID",
    "auxApplicInfo"
})
public class ReadReplyReqType
    extends GenericRSReqType
{

    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "Recipient", required = true)
    protected AddressType recipient;
    @XmlElement(name = "Sender", required = true)
    protected AddressType sender;
    @XmlElement(name = "TimeStamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "MMStatus", required = true)
    protected MmReadStatusType mmStatus;
    @XmlElement(name = "StatusText")
    protected String statusText;
    @XmlElement(name = "ApplicID")
    protected String applicID;
    @XmlElement(name = "ReplyApplicID")
    protected String replyApplicID;
    @XmlElement(name = "AuxApplicInfo")
    protected String auxApplicInfo;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the recipient property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getRecipient() {
        return recipient;
    }

    /**
     * Sets the value of the recipient property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setRecipient(AddressType value) {
        this.recipient = value;
    }

    /**
     * Gets the value of the sender property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getSender() {
        return sender;
    }

    /**
     * Sets the value of the sender property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setSender(AddressType value) {
        this.sender = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the mmStatus property.
     * 
     * @return
     *     possible object is
     *     {@link MmReadStatusType }
     *     
     */
    public MmReadStatusType getMMStatus() {
        return mmStatus;
    }

    /**
     * Sets the value of the mmStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link MmReadStatusType }
     *     
     */
    public void setMMStatus(MmReadStatusType value) {
        this.mmStatus = value;
    }

    /**
     * Gets the value of the statusText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusText() {
        return statusText;
    }

    /**
     * Sets the value of the statusText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusText(String value) {
        this.statusText = value;
    }

    /**
     * Gets the value of the applicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicID() {
        return applicID;
    }

    /**
     * Sets the value of the applicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicID(String value) {
        this.applicID = value;
    }

    /**
     * Gets the value of the replyApplicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyApplicID() {
        return replyApplicID;
    }

    /**
     * Sets the value of the replyApplicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyApplicID(String value) {
        this.replyApplicID = value;
    }

    /**
     * Gets the value of the auxApplicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxApplicInfo() {
        return auxApplicInfo;
    }

    /**
     * Sets the value of the auxApplicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxApplicInfo(String value) {
        this.auxApplicInfo = value;
    }

}
