//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.07 at 05:25:00 AM IST 
//


package com.topcoder.alu.mock.mm7.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for replaceReqType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="replaceReqType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}genericVASPRequestType">
 *       &lt;sequence>
 *         &lt;element name="MessageID" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}messageIDType"/>
 *         &lt;element name="ServiceCode" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}serviceCodeType" minOccurs="0"/>
 *         &lt;element name="TimeStamp" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="ReadReply" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="EarliestDeliveryTime" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}relativeOrAbsoluteDateType" minOccurs="0"/>
 *         &lt;element name="DistributionIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ContentClass" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}contentClassType" minOccurs="0"/>
 *         &lt;element name="DRMContent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ApplicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReplyApplicID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuxApplicInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Content" type="{http://www.3gpp.org/ftp/Specs/archive/23_series/23.140/schema/REL-6-MM7-1-4}contentReferenceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "replaceReqType", propOrder = {
    "messageID",
    "serviceCode",
    "timeStamp",
    "readReply",
    "earliestDeliveryTime",
    "distributionIndicator",
    "contentClass",
    "drmContent",
    "applicID",
    "replyApplicID",
    "auxApplicInfo",
    "content"
})
public class ReplaceReqType
    extends GenericVASPRequestType
{

    @XmlElement(name = "MessageID", required = true)
    protected String messageID;
    @XmlElement(name = "ServiceCode")
    protected ServiceCodeType serviceCode;
    @XmlElement(name = "TimeStamp")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timeStamp;
    @XmlElement(name = "ReadReply")
    protected Boolean readReply;
    @XmlElement(name = "EarliestDeliveryTime")
    protected String earliestDeliveryTime;
    @XmlElement(name = "DistributionIndicator")
    protected Boolean distributionIndicator;
    @XmlElement(name = "ContentClass")
    protected ContentClassType contentClass;
    @XmlElement(name = "DRMContent")
    protected Boolean drmContent;
    @XmlElement(name = "ApplicID")
    protected String applicID;
    @XmlElement(name = "ReplyApplicID")
    protected String replyApplicID;
    @XmlElement(name = "AuxApplicInfo")
    protected String auxApplicInfo;
    @XmlElement(name = "Content")
    protected ContentReferenceType content;

    /**
     * Gets the value of the messageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageID() {
        return messageID;
    }

    /**
     * Sets the value of the messageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageID(String value) {
        this.messageID = value;
    }

    /**
     * Gets the value of the serviceCode property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceCodeType }
     *     
     */
    public ServiceCodeType getServiceCode() {
        return serviceCode;
    }

    /**
     * Sets the value of the serviceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceCodeType }
     *     
     */
    public void setServiceCode(ServiceCodeType value) {
        this.serviceCode = value;
    }

    /**
     * Gets the value of the timeStamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeStamp() {
        return timeStamp;
    }

    /**
     * Sets the value of the timeStamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeStamp(XMLGregorianCalendar value) {
        this.timeStamp = value;
    }

    /**
     * Gets the value of the readReply property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReadReply() {
        return readReply;
    }

    /**
     * Sets the value of the readReply property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReadReply(Boolean value) {
        this.readReply = value;
    }

    /**
     * Gets the value of the earliestDeliveryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEarliestDeliveryTime() {
        return earliestDeliveryTime;
    }

    /**
     * Sets the value of the earliestDeliveryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEarliestDeliveryTime(String value) {
        this.earliestDeliveryTime = value;
    }

    /**
     * Gets the value of the distributionIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDistributionIndicator() {
        return distributionIndicator;
    }

    /**
     * Sets the value of the distributionIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDistributionIndicator(Boolean value) {
        this.distributionIndicator = value;
    }

    /**
     * Gets the value of the contentClass property.
     * 
     * @return
     *     possible object is
     *     {@link ContentClassType }
     *     
     */
    public ContentClassType getContentClass() {
        return contentClass;
    }

    /**
     * Sets the value of the contentClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentClassType }
     *     
     */
    public void setContentClass(ContentClassType value) {
        this.contentClass = value;
    }

    /**
     * Gets the value of the drmContent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDRMContent() {
        return drmContent;
    }

    /**
     * Sets the value of the drmContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDRMContent(Boolean value) {
        this.drmContent = value;
    }

    /**
     * Gets the value of the applicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApplicID() {
        return applicID;
    }

    /**
     * Sets the value of the applicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApplicID(String value) {
        this.applicID = value;
    }

    /**
     * Gets the value of the replyApplicID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplyApplicID() {
        return replyApplicID;
    }

    /**
     * Sets the value of the replyApplicID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplyApplicID(String value) {
        this.replyApplicID = value;
    }

    /**
     * Gets the value of the auxApplicInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuxApplicInfo() {
        return auxApplicInfo;
    }

    /**
     * Sets the value of the auxApplicInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuxApplicInfo(String value) {
        this.auxApplicInfo = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link ContentReferenceType }
     *     
     */
    public ContentReferenceType getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContentReferenceType }
     *     
     */
    public void setContent(ContentReferenceType value) {
        this.content = value;
    }

}
