DELETE FROM SCHED_ITEM_PUBLISH_XREF;
DELETE FROM SCHED_ITEM_PUB_XREF_HIST;
DELETE FROM SCHED_ITEM;
DELETE FROM sched_item_hist;
DELETE FROM ACTIVITY;
DELETE FROM activity_hist;
DELETE FROM ACTIVITY_TYPE;
DELETE FROM activity_type_hist;
DELETE FROM ACTIVITY_GROUP;
DELETE FROM activity_group_hist;
DELETE FROM SCHED_STATUS;
DELETE FROM SCHED_STATUS_hist;
DELETE FROM SCHED_REQUEST_STATUS;
DELETE FROM sched_request_status_hist;
COMMIT